ConnectionSettings:
  email_address: user@example.com
  password: change_me
  url: imap.example.com
  port: 993
Folders:
  inbox: INBOX
  spam_folder: SPAM
  ham_folder: HAM
  unsorted: UNSORTED
  infected_folder: INFECTED
  spam_learn: SPAM_LEARN
  ham_learn: HAM_LEARN
DaemonSettings:
  data_path: /var/lib/spamvanquisher/data
  scan_time: 300
  batch_size: 100
EmailParts:
  use_subject: true
  use_sender: true
  use_recipient: false
  use_body: true
MySQL:
  user: SpamVanquisher
  host: 127.0.0.1
  database: SpamVanquisher
  password: change_me
  port: 3306
Logging:
  log_path: logs/SpamVanquisher.log
  backup_count: 4
  CheckInterval: 300
  LogSize: 2g
